/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author Tobias
 */
public class GUI_Main extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Main
     */
    public GUI_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_title = new javax.swing.JLabel();
        jLabel_question = new javax.swing.JLabel();
        jLabel_answer = new javax.swing.JLabel();
        jTextField_answer = new javax.swing.JTextField();
        jTextField_question = new javax.swing.JTextField();
        jButton_lookUp = new javax.swing.JButton();
        jButton_next = new javax.swing.JButton();
        jButton_guess = new javax.swing.JButton();
        jButton_create = new javax.swing.JButton();
        jLabel_result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Language Trainer");
        setMaximumSize(new java.awt.Dimension(480, 320));
        setMinimumSize(new java.awt.Dimension(480, 320));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_title.setText("Language Trainer");
        getContentPane().add(jLabel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel_question.setText("Question");
        getContentPane().add(jLabel_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 119, -1, -1));

        jLabel_answer.setText("Answer");
        getContentPane().add(jLabel_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 188, -1, -1));

        jTextField_answer.setText("jTextField1");
        getContentPane().add(jTextField_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jTextField_question.setText("jTextField1");
        getContentPane().add(jTextField_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jButton_lookUp.setText("Look Up");
        getContentPane().add(jButton_lookUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jButton_next.setText("Next");
        getContentPane().add(jButton_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jButton_guess.setText("Guess");
        getContentPane().add(jButton_guess, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jButton_create.setText("Create");
        getContentPane().add(jButton_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel_result.setText("Correct/False");
        getContentPane().add(jLabel_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_create;
    private javax.swing.JButton jButton_guess;
    private javax.swing.JButton jButton_lookUp;
    private javax.swing.JButton jButton_next;
    private javax.swing.JLabel jLabel_answer;
    private javax.swing.JLabel jLabel_question;
    private javax.swing.JLabel jLabel_result;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JTextField jTextField_answer;
    private javax.swing.JTextField jTextField_question;
    // End of variables declaration//GEN-END:variables
}
